version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: tsed-example-mongoose/server:latest
    ports:
      - "8081:8081"
  mongodb:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
